### ISSUE TITLE
Fix scan-build bugs

### ISSUE THREAD

**Issue by JeremyGrieshop** [afw-org/afw#36]
`scan-build ./afwdev build --full -j`

**Comment by mike000000000** [comment]
When working on 2ec0f79 I noticed there there needs to be a tests to make sure query strings are being parsed correctly if there are not already.

**Comment by mike000000000** [comment]
I wish there was a better way to fix afw_runtime.c in 1ed2890. See the comment added for more info.

**Comment by mike000000000** [comment]
4102b22 affects authorization in afw_adaptor_impl.c. We need to review the authorization points. During this change, an authorization point was added for query in retrieve_objects and get_object. This may not be necessary since authorization already occurs for each object retrieved. This just gives to chance to say no snooping allowed before the attempt to read. If it's determined that this shouldn't happen, just remove the impl_check_authorization(&ctx, xctx); in impl_afw_adaptor_session_retrieve_objects() and impl_afw_adaptor_session_get_object(). If they stay in, we need to make sure the request object has everything necessary to make an access determination.

**Comment by mike000000000** [comment]
@JeremyGrieshop feel free to close whenever you like.

**Comment by mike000000000** [comment]
I updated the note for 0ebb6ba above to indicate that my conclusion was not true. dfc1a77 fixed both bugs.

@JeremyGrieshop you can close the bug when you are ready.
